# Generated by Django 5.1.7 on 2025-03-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0002_verse_verse_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verse',
            options={'ordering': ['verse_number']},
        ),
    ]
