# Generated by Django 5.1.7 on 2025-03-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0004_alter_verse_options_remove_verse_verse_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
