# Generated by Django 5.1.7 on 2025-03-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verses', '0005_verse_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verse',
            options={'ordering': ['chapter', 'verse_number'], 'verbose_name': 'Verse', 'verbose_name_plural': 'Verses'},
        ),
    ]
