# Generated by Django 5.1.7 on 2025-03-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['translation', 'created_at'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
    ]
