# Generated by Django 5.1.7 on 2025-03-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versetexts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='versetext',
            name='verse_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
